@baseUrl = http://localhost:3001
###
GET {{baseUrl}}
### authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123",
  "chave-maliciosa": "valor-malicioso"
}